baseURL = "https://geterindia.com/"
languageCode = "en-us"
title = "Geter India"
publishDir = "docs"

# Keep it bare: no taxonomy pages, etc.
disableKinds = ["RSS","taxonomy","term","sitemap"]
[permalinks]
  recipes = "/recipes/:slug/"
